name: dayjoy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.9+17
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.1
  flutter_html: any
  carousel_slider: ^3.0.0
  flutter_widget_from_html: any
  group_radio_button: ^1.1.0
  pull_to_refresh: any
  provider: ^4.3.3
  url_launcher: ^6.0.9
  flutter_native_image:
  flutter_slidable: ^0.5.7
  modal_bottom_sheet: ^2.0.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.0.3
  google_sign_in: ^5.0.1
  showcaseview: ^1.1.0
  otp_text_field: ^1.1.0
  youtube_player_flutter: any
  page_transition: ^1.1.7+6
  autocomplete_textfield: ^1.7.3
  flutter_elegant_number_button: ^0.0.3
  flutter_rating_bar: ^4.0.0
  razorpay_flutter: ^1.2.2
  fluttertoast: ^8.0.6
  readmore: ^2.1.0
  expandable: ^5.0.1
  shared_preferences:
  pin_code_fields: ^7.1.0
  font_awesome_flutter: ^9.0.0
  swipe_to: ^0.0.1+8
  geolocator: ^7.0.3
  file_picker: ^3.0.2+2
  flutter_facebook_login: ^3.0.0
  flutter_datetime_picker: ^1.5.1
  validators: ^3.0.0
  permission_handler: ^8.1.1
  firebase_analytics: ^8.3.4
  tutorial_coach_mark: ^1.0.3
  archive:
  image_picker: ^0.8.0+4
  firebase_storage: ^10.0.1
  flutter_typeahead: ^3.2.1
  the_apple_sign_in: ^1.1.1
  upgrader: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Dayjoy_Logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
